version: '3.8'

services:
  terraform:
    container_name: terraform-solana
    image: terraform-solana
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - ~/.aws:/root/.aws:ro
      - ~/.config/gcloud:/root/.config/gcloud:ro
    environment:
      - AWS_PROFILE=${AWS_PROFILE:-default}
      - TF_LOG=${TF_LOG:-INFO}
      - SKIP_INIT=${SKIP_INIT:-}  # Can be set to skip init
      - CI=${CI:-}  # Pass through CI environment variable
    working_dir: /workspace 