name: "Terraform Apply"

on:
  pull_request:
    types: [labeled]
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    name: "Terraform Apply"
    if: contains(github.event.pull_request.labels.*.name, 'apply')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-terraform-test
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve 