name: Terraform Lint

on:
  pull_request:
    branches: [ '*' ]

jobs:
  terraform-checks:
    name: Tflint Checks   
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.11.1
    
    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

  terraform-lint-checks:
    name: Terraform Lint
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/cache@v4
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}
    
    - uses: terraform-linters/setup-tflint@v4
      name: Setup TFLint
      with:
        tflint_version: latest
    
    - name: Show version
      run: tflint --version
    
    - name: Init TFLint
      run: tflint --init
    
    - name: Run TFLint
      run: tflint -f compact